# Generated by Django 2.2 on 2019-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20191127_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bitcoin_address',
            field=models.TextField(null=True),
        ),
    ]
