# Generated by Django 2.2 on 2020-04-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200117_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='bitcoin_address',
            new_name='home_addresss',
        ),
    ]
