# Generated by Django 2.2 on 2019-12-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191202_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='account_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='bank_name',
            field=models.TextField(null=True),
        ),
    ]
