# Generated by Django 2.2 on 2020-04-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200402_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='home_addresss',
            new_name='home_address',
        ),
    ]
