# Generated by Django 2.2 on 2019-12-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20191205_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='account_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='account_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='bank_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
